### ISSUE TITLE
related product not showing on product page.

### ISSUE THREAD

**Issue by rajeevjan1991** [Tun2U/M2_AutoRelated#2]
i have installed it and enabled this extension from admin panel but not getting related product on product page let me know if i missing any step. (please find attached image)
![screenshot 209](https://user-images.githubusercontent.com/33253321/34668674-766b6a5a-f494-11e7-8995-eed163a19cd3.png)

**Comment by nghelo** [comment]
Could you tell me your Magento version ?

**Comment by mageuser** [comment]
Same here, Magento 2.2.3 (Related product not showing on product page)

**Comment by michelve** [comment]
same here 2.2.5

**Comment by nghelo** [comment]
Try now with last release.
